openapi: 3.0.1
info:
  title: Python Execution Plugin Enhanced
  description: A plugin that allows the user to execute Python code, create Python files, install Python packages, and run unit tests using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:3333
paths:
  /api/execute-code:
    post:
      operationId: executeCode
      summary: Execute Python code
      responses:
        "200":
          description: OK
  /api/create-file:
    post:
      operationId: createFile
      summary: Create a Python file
      responses:
        "200":
          description: OK
  /api/install-package:
    post:
      operationId: installPackage
      summary: Install a Python package
      responses:
        "200":
          description: OK
  /api/run-unit-tests:
    post:
      operationId: runUnitTests
      summary: Run unit tests in a Python file
      responses:
        "200":
          description: OK